# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qh35bX3ukzMzoq3Pgu3QX1MC6G9K8KH8
"""

!pip install transformers

from transformers import BertTokenizer, BertForSequenceClassification

# Create a fine-tuned-like directory
model = BertForSequenceClassification.from_pretrained("bert-base-uncased", num_labels=3)
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

# Save model and tokenizer
model.save_pretrained("bert-finetuned-superapp")
tokenizer.save_pretrained("bert-finetuned-superapp")

# Zip it all
import shutil
shutil.make_archive("bert-finetuned-superapp", 'zip', "bert-finetuned-superapp")